# Generated by Django 6.1 on 2026-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_system",
            "0002_comment_text_alter_comment_post_alter_comment_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
