# Generated by Django 6.1 on 2026-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_system", "0003_post_hashtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="hashtag",
        ),
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True,
                max_length=200,
                related_name="articles",
                to="media_system.hashtag",
            ),
        ),
    ]
