# Generated by Django 6.1 on 2026-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_system", "0004_hashtag_remove_post_hashtag_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="hashtag",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
