# Generated by Django 6.1 on 2026-08-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_system", "0005_alter_hashtag_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
