# Generated by Django 6.1 on 2026-08-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_system", "0006_post_is_published_post_publish_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="publish_at",
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
