version: "3.8"
services:

  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - "6379:6379"

  webapp:
    build: .
    container_name: wa01
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis


  celery:
    build: .
    container_name: cl01
    volumes:
      - .:/webapp
    command: celery -A Social_media_API worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
