# Generated by Django 6.1 on 2026-08-11 13:56

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_user_username_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", User.models.UserManager()),
            ],
        ),
    ]
